{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPVZeU7VIH0OPz01l0o7RF5",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/joeycarlin3/ai-poc-team-h2p/blob/main/interview_app_code.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 384
        },
        "id": "9xUUh6YS0HCe",
        "outputId": "f41d5051-ee9a-42aa-dc17-5a374864c5c3"
      },
      "outputs": [
        {
          "output_type": "error",
          "ename": "ModuleNotFoundError",
          "evalue": "No module named 'streamlit'",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
            "\u001b[0;32m/tmp/ipython-input-3602481836.py\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     18\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mtyping\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mOptional\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     19\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 20\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mstreamlit\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mst\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     21\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mstreamlit_mic_recorder\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mmic_recorder\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     22\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'streamlit'",
            "",
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0;32m\nNOTE: If your import is failing due to a missing package, you can\nmanually install dependencies using either !pip or !apt.\n\nTo view examples of installing some common dependencies, click the\n\"Open Examples\" button below.\n\u001b[0;31m---------------------------------------------------------------------------\u001b[0m\n"
          ],
          "errorDetails": {
            "actions": [
              {
                "action": "open_url",
                "actionText": "Open Examples",
                "url": "/notebooks/snippets/importing_libraries.ipynb"
              }
            ]
          }
        }
      ],
      "source": [
        "# streamlit_interview_coach.py\n",
        "# Copy this file into Colab (or your editor), install dependencies, push to GitHub and run with Streamlit.\n",
        "# Usage:\n",
        "#   - Locally: `streamlit run streamlit_interview_coach.py`\n",
        "#   - Streamlit Cloud: add GEMINI_API_KEY to your app secrets as \"GEMINI_API_KEY\"\n",
        "\n",
        "# Colab note: To run Streamlit inside Colab for quick dev you can use ngrok or the Colab Streamlit helper;\n",
        "# but for production / easy deployment push the file to GitHub and deploy on Streamlit Cloud or run locally.\n",
        "\n",
        "# ---------------------------\n",
        "# Install (Colab) - uncomment & run once in a notebook cell\n",
        "# ---------------------------\n",
        "# !pip install --upgrade google-genai streamlit streamlit-mic-recorder\n",
        "\n",
        "import os\n",
        "import tempfile\n",
        "import base64\n",
        "from typing import Optional\n",
        "\n",
        "import streamlit as st\n",
        "from streamlit_mic_recorder import mic_recorder\n",
        "\n",
        "# GenAI (Gemini) Python SDK\n",
        "# modern package name: google-genai (imported as `from google import genai`)\n",
        "try:\n",
        "    from google import genai\n",
        "    from google.genai import types\n",
        "except Exception:\n",
        "    # If import fails, the user must pip install google-genai\n",
        "    st.error(\"Missing google-genai SDK. In Colab run: pip install google-genai\")\n",
        "    st.stop()\n",
        "\n",
        "# ---------------------------\n",
        "# Page config\n",
        "# ---------------------------\n",
        "st.set_page_config(page_title=\"AI Interview Coach\", page_icon=\"🎙️\", layout=\"centered\")\n",
        "\n",
        "st.title(\"🎙️ AI Interview Coach — practice, record, get feedback\")\n",
        "\n",
        "st.markdown(\n",
        "    \"\"\"\n",
        "    This app:\n",
        "    1. generates a behavioral interview question for your career goal;\n",
        "    2. lets you record your spoken answer in-browser;\n",
        "    3. transcribes the recording using Gemini's audio capabilities;\n",
        "    4. returns AI feedback based on the STAR method.\n",
        "\n",
        "    **Before you run:** Put your Gemini API key into Streamlit secrets as `GEMINI_API_KEY` (or set the env var `GEMINI_API_KEY`).\n",
        "    \"\"\"\n",
        ")\n",
        "\n",
        "# ---------------------------\n",
        "# Configure Gemini API\n",
        "# ---------------------------\n",
        "GEMINI_API_KEY = None\n",
        "\n",
        "# Prefer Streamlit secrets (works on Streamlit Cloud). Fallback to environment variable.\n",
        "if \"GEMINI_API_KEY\" in st.secrets:\n",
        "    GEMINI_API_KEY = st.secrets[\"GEMINI_API_KEY\"]\n",
        "elif os.getenv(\"GEMINI_API_KEY\"):\n",
        "    GEMINI_API_KEY = os.getenv(\"GEMINI_API_KEY\")\n",
        "else:\n",
        "    st.warning(\"Gemini API key not found. Add it to Streamlit secrets as 'GEMINI_API_KEY' or set the environment variable.\")\n",
        "    st.stop()\n",
        "\n",
        "# Initialize client\n",
        "try:\n",
        "    client = genai.Client(api_key=GEMINI_API_KEY)\n",
        "except Exception as e:\n",
        "    st.error(f\"Failed to initialize Gemini client: {e}\")\n",
        "    st.stop()\n",
        "\n",
        "# Choose a model - you can change this to another Gemini model that supports audio (see docs)\n",
        "MODEL = \"gemini-2.0-flash\"  # change if you prefer another supported model\n",
        "\n",
        "# ---------------------------\n",
        "# Helper functions\n",
        "# ---------------------------\n",
        "def generate_behavioral_question(career_goal: str) -> str:\n",
        "    prompt = f\"Generate one concise behavioral interview question for a candidate aspiring to be a {career_goal}. Keep it clear and focused.\"\n",
        "    try:\n",
        "        resp = client.models.generate_content(model=MODEL, contents=[prompt])\n",
        "        # Most SDK responses expose .text — fallback to parsing candidates if needed\n",
        "        if hasattr(resp, \"text\") and resp.text:\n",
        "            return resp.text.strip()\n",
        "        # Best-effort parsing if the SDK returns a more detailed object\n",
        "        try:\n",
        "            # Some responses include candidates -> content parts\n",
        "            return resp.candidates[0].content[0].text.strip()\n",
        "        except Exception:\n",
        "            return \"Tell me about a time you had to manage a difficult stakeholder.\"\n",
        "    except Exception as e:\n",
        "        st.error(f\"Error generating question: {e}\")\n",
        "        return \"Tell me about a time you had to manage a difficult stakeholder.\"\n",
        "\n",
        "def transcribe_audio_bytes(audio_bytes: bytes, mime_type: str = \"audio/wav\") -> Optional[str]:\n",
        "    \"\"\"\n",
        "    Send inline audio bytes to Gemini via generate_content with a Part.from_bytes.\n",
        "    Works for files < ~20MB (for larger files use cloud storage + file reference).\n",
        "    Returns transcript text or None on error.\n",
        "    \"\"\"\n",
        "    try:\n",
        "        # Build a user prompt asking for a transcription with light formatting.\n",
        "        user_prompt = (\n",
        "            \"Please transcribe the attached audio. Provide a clean transcription. \"\n",
        "            \"If possible, add short timecodes (mm:ss) every ~20 seconds and label the speaker as 'Candidate'.\"\n",
        "        )\n",
        "\n",
        "        audio_part = types.Part.from_bytes(data=audio_bytes, mime_type=mime_type)\n",
        "\n",
        "        contents = [\n",
        "            user_prompt,\n",
        "            audio_part\n",
        "        ]\n",
        "\n",
        "        resp = client.models.generate_content(model=MODEL, contents=contents)\n",
        "        # Try .text first\n",
        "        if hasattr(resp, \"text\") and resp.text:\n",
        "            return resp.text.strip()\n",
        "        # Try parsing candidates\n",
        "        try:\n",
        "            return resp.candidates[0].content[0].text.strip()\n",
        "        except Exception:\n",
        "            # Last resort: stringify the response object\n",
        "            return str(resp)\n",
        "    except Exception as e:\n",
        "        st.error(f\"Transcription error: {e}\")\n",
        "        return None\n",
        "\n",
        "def parse_data_url_or_bytes(audio_obj) -> Optional[bytes]:\n",
        "    \"\"\"\n",
        "    The streamlit mic recorder returns different shapes depending on versions:\n",
        "      - sometimes a dict with 'data' or 'blob' or 'file' containing a data:audio/...;base64,... string\n",
        "      - sometimes raw bytes\n",
        "    This helper attempts to extract raw bytes.\n",
        "    \"\"\"\n",
        "    if audio_obj is None:\n",
        "        return None\n",
        "\n",
        "    # If it's a dict with a data URL:\n",
        "    if isinstance(audio_obj, dict):\n",
        "        # common keys: 'data', 'file', 'blob', 'bytes'\n",
        "        for key in (\"data\", \"file\", \"blob\", \"bytes\", \"wav_bytes\"):\n",
        "            if key in audio_obj and audio_obj[key]:\n",
        "                val = audio_obj[key]\n",
        "                # If bytes already\n",
        "                if isinstance(val, (bytes, bytearray)):\n",
        "                    return bytes(val)\n",
        "                # If it's a data URL string:\n",
        "                if isinstance(val, str) and val.startswith(\"data:audio\"):\n",
        "                    try:\n",
        "                        header, b64 = val.split(\",\", 1)\n",
        "                        return base64.b64decode(b64)\n",
        "                    except Exception:\n",
        "                        # If it's plain base64 without header\n",
        "                        try:\n",
        "                            return base64.b64decode(val)\n",
        "                        except Exception:\n",
        "                            return None\n",
        "                # If it's a plain base64 string:\n",
        "                if isinstance(val, str):\n",
        "                    try:\n",
        "                        return base64.b64decode(val)\n",
        "                    except Exception:\n",
        "                        continue\n",
        "\n",
        "    # If it's raw bytes\n",
        "    if isinstance(audio_obj, (bytes, bytearray)):\n",
        "        return bytes(audio_obj)\n",
        "\n",
        "    # If it's a string that might be a data URL\n",
        "    if isinstance(audio_obj, str) and audio_obj.startswith(\"data:audio\"):\n",
        "        try:\n",
        "            _, b64 = audio_obj.split(\",\", 1)\n",
        "            return base64.b64decode(b64)\n",
        "        except Exception:\n",
        "            return None\n",
        "\n",
        "    return None\n",
        "\n",
        "# ---------------------------\n",
        "# Streamlit UI\n",
        "# ---------------------------\n",
        "st.header(\"1) Pick a role & get a behavioral question\")\n",
        "career_goal = st.text_input(\"Enter career goal (e.g. Software Engineer, Product Manager):\", value=\"Software Engineer\")\n",
        "if st.button(\"Get a question\") or career_goal and \"question\" not in st.session_state:\n",
        "    st.session_state.question = generate_behavioral_question(career_goal)\n",
        "\n",
        "if \"question\" in st.session_state:\n",
        "    st.subheader(\"Your practice question\")\n",
        "    st.info(st.session_state.question)\n",
        "\n",
        "    st.markdown(\"---\")\n",
        "    st.header(\"2) Record your answer (in browser)\")\n",
        "    st.write(\"Click **Start Recording**, answer the question out loud, then **Stop Recording**. When ready, transcribe & get feedback.\")\n",
        "    audio = mic_recorder(\n",
        "        start_prompt=\"Start Recording\",\n",
        "        stop_prompt=\"Stop Recording\",\n",
        "        key=\"recorder\"\n",
        "    )\n",
        "\n",
        "    if audio:\n",
        "        st.success(\"Recording captured — click play to listen.\")\n",
        "        # The recorder often provides playable bytes in a 'data' or 'file' key — show audio player if possible\n",
        "        try:\n",
        "            # If the recorder gives a Data URL\n",
        "            if isinstance(audio, dict) and (\"data\" in audio or \"file\" in audio):\n",
        "                # pick data/file\n",
        "                data_str = audio.get(\"data\") or audio.get(\"file\")\n",
        "                if isinstance(data_str, str) and data_str.startswith(\"data:audio\"):\n",
        "                    st.audio(data_str)\n",
        "                else:\n",
        "                    # maybe bytes object\n",
        "                    st.audio(audio.get(\"bytes\") or audio.get(\"wav_bytes\"))\n",
        "            else:\n",
        "                # raw bytes\n",
        "                st.audio(audio)\n",
        "        except Exception:\n",
        "            st.info(\"Audio player could not be displayed (still ok — transcription will be attempted).\")\n",
        "\n",
        "        st.markdown(\"### 3) Transcribe (auto) and edit (optional)\")\n",
        "        # Extract bytes robustly\n",
        "        audio_bytes = parse_data_url_or_bytes(audio)\n",
        "        if audio_bytes is None:\n",
        "            st.warning(\"Couldn't parse recorded audio automatically. If transcription fails, you can paste a typed answer below.\")\n",
        "        else:\n",
        "            # Save to a temp file for debugging or if needed\n",
        "            tmpf = tempfile.NamedTemporaryFile(delete=False, suffix=\".wav\")\n",
        "            tmpf.write(audio_bytes)\n",
        "            tmpf.flush()\n",
        "            tmpf.close()\n",
        "            st.caption(f\"Saved recording to temporary file: {tmpf.name}\")\n",
        "\n",
        "            if st.button(\"Transcribe recording\"):\n",
        "                with st.spinner(\"Transcribing with Gemini...\"):\n",
        "                    transcription = transcribe_audio_bytes(audio_bytes, mime_type=\"audio/wav\")\n",
        "                    if transcription:\n",
        "                        st.subheader(\"Transcribed text (you can edit before requesting feedback)\")\n",
        "                        st.session_state.transcription = transcription\n",
        "                        st.text_area(\"Edit transcription:\", value=st.session_state.transcription, height=200, key=\"trans_box\")\n",
        "                    else:\n",
        "                        st.error(\"Transcription failed. Please type your answer manually below.\")\n",
        "\n",
        "        st.markdown(\"### 4) Or type / edit your answer for feedback\")\n",
        "        typed_answer = st.text_area(\"Type or paste your final answer here (used for feedback):\", value=st.session_state.get(\"transcription\", \"\"), height=200)\n",
        "\n",
        "        if st.button(\"Get AI feedback\"):\n",
        "            if not typed_answer or typed_answer.strip() == \"\":\n",
        "                st.warning(\"Please provide an answer to get feedback (either transcribe first or type your answer).\")\n",
        "            else:\n",
        "                with st.spinner(\"Generating AI feedback...\"):\n",
        "                    fb_prompt = f\"\"\"\n",
        "                    Provide actionable, constructive interview feedback for this candidate answer.\n",
        "                    Question: \"{st.session_state.question}\"\n",
        "                    Candidate's answer: \"{typed_answer}\"\n",
        "\n",
        "                    Use the STAR structure to evaluate (Situation, Task, Action, Result). Give:\n",
        "                    1) A short summary (1-2 sentences).\n",
        "                    2) Strengths (bulleted).\n",
        "                    3) Specific concrete improvements with examples and suggested alternative phrasings.\n",
        "                    4) A final short, encouraging tip for a follow-up question the interviewer might ask.\n",
        "                    Keep the response professional and candidate-friendly.\n",
        "                    \"\"\"\n",
        "                    try:\n",
        "                        fb_resp = client.models.generate_content(model=MODEL, contents=[fb_prompt])\n",
        "                        if hasattr(fb_resp, \"text\") and fb_resp.text:\n",
        "                            feedback_text = fb_resp.text.strip()\n",
        "                        else:\n",
        "                            try:\n",
        "                                feedback_text = fb_resp.candidates[0].content[0].text.strip()\n",
        "                            except Exception:\n",
        "                                feedback_text = str(fb_resp)\n",
        "                        st.subheader(\"AI Feedback\")\n",
        "                        st.write(feedback_text)\n",
        "                    except Exception as e:\n",
        "                        st.error(f\"Failed to generate feedback: {e}\")\n",
        "\n",
        "    else:\n",
        "        st.info(\"Press Start Recording to capture audio.\")\n",
        "\n",
        "st.markdown(\"---\")\n",
        "st.caption(\"This demo sends inline audio bytes to Gemini for transcription (for small files). For large audio files (> ~20MB) use Cloud Storage + a file URI per the Gemini/Vertex AI docs.\")\n"
      ]
    }
  ]
}